function OAS_RICH(position) {
if (position == 'x01') {
document.write ('<!--inib-->\n');
document.write ('<img src="http://uniprix.nouvelobs.com/5/BIBLIOBS/RG_DOCUMENTS/L21/15807922/x01/OasDefault/Inib_x01/inibator.html/76682f4f706b2b32323451414142446c?_RM_EMPTY_&ref=www.google.com.ar&key=20111026.OBS3314" style="display: none">');
}
if (position == 'x10') {
document.write ('<!--inib--><img src="http://uniprix.nouvelobs.com/5/BIBLIOBS/RG_DOCUMENTS/L21/1725146692/x10/OasDefault/Inib_x10/inibator.html/76682f4f706b2b32323451414142446c?_RM_EMPTY_&ref=www.google.com.ar&key=20111026.OBS3314" style="display: none">');
}
if (position == 'x20') {
document.write ('<!--inib--><img src="http://uniprix.nouvelobs.com/5/BIBLIOBS/RG_DOCUMENTS/L21/1214711182/x20/OasDefault/Inib_x20/inibator.html/76682f4f706b2b32323451414142446c?_RM_EMPTY_&ref=www.google.com.ar&key=20111026.OBS3314" style="display: none">');
}
if (position == 'Top2') {
document.write ('<!--\n');
document.write ('Support: http://uniprix.nouvelobs.com#OasDefault/Pocket-Minier_Bibliobs_Mb_0512#Pocket-Minier_Bibliobs_Mb_0512#Pocket-Minier_Bibliobs_Mb_0512.html#0262d#1224601474#599#S#Top2#BIBLIOBS/RG_DOCUMENTS/L21##\n');
document.write ('--><script id="extFlashTop21" type="text/javascript" src="http://uniprix.nouvelobs.com/0/TFSMflashobject.js"></script>\n');
document.write ('<script type="text/javascript">\n');
document.write ('<!--\n');
document.write ('\n');
document.write ('var flash_fileTop2 = ');
document.write ("'");
document.write ('megaban-minier-glace-2.swf');
document.write ("'");
document.write (';\n');
document.write ('var image_fileTop2 = ');
document.write ("'");
document.write ('');
document.write ("'");
document.write (';\n');
document.write ('var clicktagTop2 = ');
document.write ("'");
document.write ('clickTag');
document.write ("'");
document.write (';\n');
document.write ('var dim = ');
document.write ("'");
document.write (' WIDTH=728 HEIGHT=90');
document.write ("'");
document.write (';\n');
document.write ('var widthTop2 = dim.replace(/width="*([0-9]*)"*[ ]*height="*([0-9]*)"*.*/i, ');
document.write ("'");
document.write ('$1');
document.write ("'");
document.write (') ;\n');
document.write ('var heightTop2 = dim.replace(/width="*([0-9]*)"*[ ]*height="*([0-9]*)"*.*/i, ');
document.write ("'");
document.write ('$2');
document.write ("'");
document.write (') ;\n');
document.write ('var wmodeTop2 = ');
document.write ("'");
document.write ('opaque');
document.write ("'");
document.write (';\n');
document.write ('\n');
document.write ('if(!document.body)\n');
document.write ('document.write("<html><body>");\n');
document.write ('OASd = document;\n');
document.write ('var plug = false;\n');
document.write ('var flashVersion = -1;\n');
document.write ('var minFlashVersion = 6;\n');
document.write ('if(navigator.plugins != null && navigator.plugins.length > 0){flashVersion =(navigator.plugins["Shockwave Flash 2.0"] || navigator.plugins["Shockwave Flash"]) ? navigator.plugins["Shockwave Flash" +(navigator.plugins["Shockwave Flash 2.0"] ? " 2.0" : "")].description.split(" ")[2].split(".")[0] : -1;\n');
document.write ('plug = flashVersion >= minFlashVersion;}\n');
document.write ('else if(navigator.userAgent.toLowerCase().indexOf("webtv/2.6") != -1){flashVersion = 4;plug = flashVersion >= minFlashVersion;}\n');
document.write ('else if(navigator.userAgent.toLowerCase().indexOf("webtv/2.5") != -1){flashVersion = 3;plug = flashVersion >= minFlashVersion;}\n');
document.write ('else if(navigator.userAgent.toLowerCase().indexOf("webtv") != -1){flashVersion = 2;plug = flashVersion >= minFlashVersion;}\n');
document.write ('else if((navigator.appVersion.indexOf("MSIE") != -1) &&(navigator.appVersion.toLowerCase().indexOf("win") != -1) &&(navigator.userAgent.indexOf("Opera") == -1)){var oasobj;\n');
document.write ('var exc;\n');
document.write ('try{oasobj = new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7");\n');
document.write ('flashVersion = oasobj.GetVariable("$version");} catch(exc){try{oasobj = new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");\n');
document.write ('version = "WIN 6,0,21,0";\n');
document.write ('oasobj.AllowScriptAccess = "always";\n');
document.write ('flashVersion = oasobj.GetVariable("$version");} catch(exc){try{oasobj = new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3");\n');
document.write ('flashVersion = oasobj.GetVariable("$version");} catch(exc){try{oasobj = new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3");\n');
document.write ('flashVersion = "WIN 3,0,18,0";} catch(exc){try{oasobj = new ActiveXObject("ShockwaveFlash.ShockwaveFlash");\n');
document.write ('flashVersion = "WIN 2,0,0,11";} catch(exc){flashVersion = -1;}}}}}\n');
document.write ('plug =(flashVersion != -1)? flashVersion.split(" ")[1].split(",")[0] >= minFlashVersion : false;}\n');
document.write ('\n');
document.write ('if(plug)\n');
document.write ('{\n');
document.write ('document.write("<div id=\\');
document.write ('"FinContentTop21\\');
document.write ('"></div>");\n');
document.write ('function loadFlashTop21(){\n');
document.write ('if(navigator.userAgent.indexOf("MSIE") != -1 && navigator.userAgent.indexOf("Opera") == -1){\n');
document.write ('\n');
document.write ('if (extFlashTop21.readyState == "complete")\n');
document.write ('{\n');
document.write ('FlashObject("http://uniprix.nouvelobs.com/0/OasDefault/Pocket-Minier_Bibliobs_Mb_0512/"+flash_fileTop2+"?"+clicktagTop2+"=http://uniprix.nouvelobs.com/5c/BIBLIOBS/RG_DOCUMENTS/L21/2087175436/Top2/OasDefault/Pocket-Minier_Bibliobs_Mb_0512/Pocket-Minier_Bibliobs_Mb_0512.html/76682f4f706b2b32323451414142446c?ref=www.google.com.ar&key=20111026.OBS3314", "OAS_AD_Top2", "width="+widthTop2+" height="+heightTop2, wmodeTop2, "clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" ,"6", "FinContentTop21");\n');
document.write ('extFlashTop21.onreadystatechange = "";\n');
document.write ('}\n');
document.write ('\n');
document.write ('extFlashTop21.onreadystatechange = loadFlashTop21;\n');
document.write ('}\n');
document.write ('else\n');
document.write ('{\n');
document.write ('OASfp=" Menu=FALSE swModifyReport=TRUE width="+widthTop2+" height="+heightTop2+" ";\n');
document.write ('OASd.write("<object id=\\');
document.write ('"techsource_Top2\\');
document.write ('" classid=\\');
document.write ('"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\\');
document.write ('" codebase=\\');
document.write ('"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0\\');
document.write ('""+OASfp+">");\n');
document.write ('OASd.write("<param name=src value=\\');
document.write ('"http://uniprix.nouvelobs.com/0/OasDefault/Pocket-Minier_Bibliobs_Mb_0512/"+flash_fileTop2+"\\');
document.write ('"><param name=allowScriptAccess value=always><param name=quality value=autohigh><param name=loop value=true><param name=play value=true><param name=menu value=false><param name=wmode value="+wmodeTop2+"><param name=FlashVars value=\\');
document.write ('""+clicktagTop2+"=http://uniprix.nouvelobs.com/5c/BIBLIOBS/RG_DOCUMENTS/L21/2087175436/Top2/OasDefault/Pocket-Minier_Bibliobs_Mb_0512/Pocket-Minier_Bibliobs_Mb_0512.html/76682f4f706b2b32323451414142446c?ref=www.google.com.ar&key=20111026.OBS3314\\');
document.write ('">");\n');
document.write ('OASd.write("<embed src=\\');
document.write ('"http://uniprix.nouvelobs.com/0/OasDefault/Pocket-Minier_Bibliobs_Mb_0512/"+flash_fileTop2+"\\');
document.write ('""+OASfp+"pluginspage=\\');
document.write ('"http://www.macromedia.com/shockwave\\');
document.write ('" type=\\');
document.write ('"application/x-shockwave-flash\\');
document.write ('" width="+widthTop2+" height="+heightTop2+" PLAY=true LOOP=true QUALITY=autohigh WMODE="+wmodeTop2+" FlashVars=\\');
document.write ('""+clicktagTop2+"=http://uniprix.nouvelobs.com/5c/BIBLIOBS/RG_DOCUMENTS/L21/2087175436/Top2/OasDefault/Pocket-Minier_Bibliobs_Mb_0512/Pocket-Minier_Bibliobs_Mb_0512.html/76682f4f706b2b32323451414142446c?ref=www.google.com.ar&key=20111026.OBS3314\\');
document.write ('" allowScriptAccess=always>");\n');
document.write ('OASd.write("</embed></object>");\n');
document.write ('}\n');
document.write ('\n');
document.write ('}\n');
document.write ('loadFlashTop21();\n');
document.write ('}\n');
document.write ('else\n');
document.write ('{\n');
document.write ('OASd.write("<a href=\\');
document.write ('"http://uniprix.nouvelobs.com/5c/BIBLIOBS/RG_DOCUMENTS/L21/2087175436/Top2/OasDefault/Pocket-Minier_Bibliobs_Mb_0512/Pocket-Minier_Bibliobs_Mb_0512.html/76682f4f706b2b32323451414142446c?ref=www.google.com.ar&key=20111026.OBS3314\\');
document.write ('" target=\\');
document.write ('"_blank\\');
document.write ('"><img src=\\');
document.write ('"http://uniprix.nouvelobs.com/0/OasDefault/Pocket-Minier_Bibliobs_Mb_0512/"+image_fileTop2+"\\');
document.write ('" width="+widthTop2+" height="+heightTop2+" border=0 alt=\\');
document.write ('"megaban-minier-glace-2.swf\\');
document.write ('"></a>");}\n');
document.write ('if(!document.body)\n');
document.write ('document.write("</body></html>");\n');
document.write ('//-->\n');
document.write ('</script><img src="http://uniprix.nouvelobs.com/5/BIBLIOBS/RG_DOCUMENTS/L21/2087175436/Top2/OasDefault/Pocket-Minier_Bibliobs_Mb_0512/Pocket-Minier_Bibliobs_Mb_0512.html/76682f4f706b2b32323451414142446c?_RM_EMPTY_&ref=www.google.com.ar&key=20111026.OBS3314" style="display: none">');
}
if (position == 'Right') {
document.write ('<!--inib--><img src="http://uniprix.nouvelobs.com/5/BIBLIOBS/RG_DOCUMENTS/L21/1423697768/Right/OasDefault/Inib_right/inibator.html/76682f4f706b2b32323451414142446c?_RM_EMPTY_&ref=www.google.com.ar&key=20111026.OBS3314" style="display: none">');
}
if (position == 'Middle') {
document.write ('<!--\n');
document.write ('Support: http://uniprix.nouvelobs.com#OasDefault/AP_NO_ABO_DECOUVERTE_MULTI_0709#carte_pv_1111#carte_pv_1111.html#0262d#1224601474#599#S#Middle#BIBLIOBS/RG_DOCUMENTS/L21##\n');
document.write ('--><script id="extFlashMiddle1" type="text/javascript" src="http://uniprix.nouvelobs.com/0/TFSMflashobject.js"></script>\n');
document.write ('<script type="text/javascript">\n');
document.write ('<!--\n');
document.write ('\n');
document.write ('var flash_fileMiddle = ');
document.write ("'");
document.write ('PAVE-CARTE.swf');
document.write ("'");
document.write (';\n');
document.write ('var image_fileMiddle = ');
document.write ("'");
document.write ('');
document.write ("'");
document.write (';\n');
document.write ('var clicktagMiddle = ');
document.write ("'");
document.write ('clickTag');
document.write ("'");
document.write (';\n');
document.write ('var dim = ');
document.write ("'");
document.write (' WIDTH=300 HEIGHT=250');
document.write ("'");
document.write (';\n');
document.write ('var widthMiddle = dim.replace(/width="*([0-9]*)"*[ ]*height="*([0-9]*)"*.*/i, ');
document.write ("'");
document.write ('$1');
document.write ("'");
document.write (') ;\n');
document.write ('var heightMiddle = dim.replace(/width="*([0-9]*)"*[ ]*height="*([0-9]*)"*.*/i, ');
document.write ("'");
document.write ('$2');
document.write ("'");
document.write (') ;\n');
document.write ('var wmodeMiddle = ');
document.write ("'");
document.write ('opaque');
document.write ("'");
document.write (';\n');
document.write ('\n');
document.write ('if(!document.body)\n');
document.write ('document.write("<html><body>");\n');
document.write ('OASd = document;\n');
document.write ('var plug = false;\n');
document.write ('var flashVersion = -1;\n');
document.write ('var minFlashVersion = 6;\n');
document.write ('if(navigator.plugins != null && navigator.plugins.length > 0){flashVersion =(navigator.plugins["Shockwave Flash 2.0"] || navigator.plugins["Shockwave Flash"]) ? navigator.plugins["Shockwave Flash" +(navigator.plugins["Shockwave Flash 2.0"] ? " 2.0" : "")].description.split(" ")[2].split(".")[0] : -1;\n');
document.write ('plug = flashVersion >= minFlashVersion;}\n');
document.write ('else if(navigator.userAgent.toLowerCase().indexOf("webtv/2.6") != -1){flashVersion = 4;plug = flashVersion >= minFlashVersion;}\n');
document.write ('else if(navigator.userAgent.toLowerCase().indexOf("webtv/2.5") != -1){flashVersion = 3;plug = flashVersion >= minFlashVersion;}\n');
document.write ('else if(navigator.userAgent.toLowerCase().indexOf("webtv") != -1){flashVersion = 2;plug = flashVersion >= minFlashVersion;}\n');
document.write ('else if((navigator.appVersion.indexOf("MSIE") != -1) &&(navigator.appVersion.toLowerCase().indexOf("win") != -1) &&(navigator.userAgent.indexOf("Opera") == -1)){var oasobj;\n');
document.write ('var exc;\n');
document.write ('try{oasobj = new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7");\n');
document.write ('flashVersion = oasobj.GetVariable("$version");} catch(exc){try{oasobj = new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");\n');
document.write ('version = "WIN 6,0,21,0";\n');
document.write ('oasobj.AllowScriptAccess = "always";\n');
document.write ('flashVersion = oasobj.GetVariable("$version");} catch(exc){try{oasobj = new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3");\n');
document.write ('flashVersion = oasobj.GetVariable("$version");} catch(exc){try{oasobj = new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3");\n');
document.write ('flashVersion = "WIN 3,0,18,0";} catch(exc){try{oasobj = new ActiveXObject("ShockwaveFlash.ShockwaveFlash");\n');
document.write ('flashVersion = "WIN 2,0,0,11";} catch(exc){flashVersion = -1;}}}}}\n');
document.write ('plug =(flashVersion != -1)? flashVersion.split(" ")[1].split(",")[0] >= minFlashVersion : false;}\n');
document.write ('\n');
document.write ('if(plug)\n');
document.write ('{\n');
document.write ('document.write("<div id=\\');
document.write ('"FinContentMiddle1\\');
document.write ('"></div>");\n');
document.write ('function loadFlashMiddle1(){\n');
document.write ('if(navigator.userAgent.indexOf("MSIE") != -1 && navigator.userAgent.indexOf("Opera") == -1){\n');
document.write ('\n');
document.write ('if (extFlashMiddle1.readyState == "complete")\n');
document.write ('{\n');
document.write ('FlashObject("http://uniprix.nouvelobs.com/0/OasDefault/AP_NO_ABO_DECOUVERTE_MULTI_0709/"+flash_fileMiddle+"?"+clicktagMiddle+"=http://uniprix.nouvelobs.com/5c/BIBLIOBS/RG_DOCUMENTS/L21/1745190298/Middle/OasDefault/AP_NO_ABO_DECOUVERTE_MULTI_0709/carte_pv_1111.html/76682f4f706b2b32323451414142446c?ref=www.google.com.ar&key=20111026.OBS3314", "OAS_AD_Middle", "width="+widthMiddle+" height="+heightMiddle, wmodeMiddle, "clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" ,"6", "FinContentMiddle1");\n');
document.write ('extFlashMiddle1.onreadystatechange = "";\n');
document.write ('}\n');
document.write ('\n');
document.write ('extFlashMiddle1.onreadystatechange = loadFlashMiddle1;\n');
document.write ('}\n');
document.write ('else\n');
document.write ('{\n');
document.write ('OASfp=" Menu=FALSE swModifyReport=TRUE width="+widthMiddle+" height="+heightMiddle+" ";\n');
document.write ('OASd.write("<object id=\\');
document.write ('"techsource_Middle\\');
document.write ('" classid=\\');
document.write ('"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\\');
document.write ('" codebase=\\');
document.write ('"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0\\');
document.write ('""+OASfp+">");\n');
document.write ('OASd.write("<param name=src value=\\');
document.write ('"http://uniprix.nouvelobs.com/0/OasDefault/AP_NO_ABO_DECOUVERTE_MULTI_0709/"+flash_fileMiddle+"\\');
document.write ('"><param name=allowScriptAccess value=always><param name=quality value=autohigh><param name=loop value=true><param name=play value=true><param name=menu value=false><param name=wmode value="+wmodeMiddle+"><param name=FlashVars value=\\');
document.write ('""+clicktagMiddle+"=http://uniprix.nouvelobs.com/5c/BIBLIOBS/RG_DOCUMENTS/L21/1745190298/Middle/OasDefault/AP_NO_ABO_DECOUVERTE_MULTI_0709/carte_pv_1111.html/76682f4f706b2b32323451414142446c?ref=www.google.com.ar&key=20111026.OBS3314\\');
document.write ('">");\n');
document.write ('OASd.write("<embed src=\\');
document.write ('"http://uniprix.nouvelobs.com/0/OasDefault/AP_NO_ABO_DECOUVERTE_MULTI_0709/"+flash_fileMiddle+"\\');
document.write ('""+OASfp+"pluginspage=\\');
document.write ('"http://www.macromedia.com/shockwave\\');
document.write ('" type=\\');
document.write ('"application/x-shockwave-flash\\');
document.write ('" width="+widthMiddle+" height="+heightMiddle+" PLAY=true LOOP=true QUALITY=autohigh WMODE="+wmodeMiddle+" FlashVars=\\');
document.write ('""+clicktagMiddle+"=http://uniprix.nouvelobs.com/5c/BIBLIOBS/RG_DOCUMENTS/L21/1745190298/Middle/OasDefault/AP_NO_ABO_DECOUVERTE_MULTI_0709/carte_pv_1111.html/76682f4f706b2b32323451414142446c?ref=www.google.com.ar&key=20111026.OBS3314\\');
document.write ('" allowScriptAccess=always>");\n');
document.write ('OASd.write("</embed></object>");\n');
document.write ('}\n');
document.write ('\n');
document.write ('}\n');
document.write ('loadFlashMiddle1();\n');
document.write ('}\n');
document.write ('else\n');
document.write ('{\n');
document.write ('OASd.write("<a href=\\');
document.write ('"http://uniprix.nouvelobs.com/5c/BIBLIOBS/RG_DOCUMENTS/L21/1745190298/Middle/OasDefault/AP_NO_ABO_DECOUVERTE_MULTI_0709/carte_pv_1111.html/76682f4f706b2b32323451414142446c?ref=www.google.com.ar&key=20111026.OBS3314\\');
document.write ('" target=\\');
document.write ('"_blank\\');
document.write ('"><img src=\\');
document.write ('"http://uniprix.nouvelobs.com/0/OasDefault/AP_NO_ABO_DECOUVERTE_MULTI_0709/"+image_fileMiddle+"\\');
document.write ('" width="+widthMiddle+" height="+heightMiddle+" border=0 alt=\\');
document.write ('"PAVE-CARTE.swf\\');
document.write ('"></a>");}\n');
document.write ('if(!document.body)\n');
document.write ('document.write("</body></html>");\n');
document.write ('//-->\n');
document.write ('</script><img src="http://uniprix.nouvelobs.com/5/BIBLIOBS/RG_DOCUMENTS/L21/1745190298/Middle/OasDefault/AP_NO_ABO_DECOUVERTE_MULTI_0709/carte_pv_1111.html/76682f4f706b2b32323451414142446c?_RM_EMPTY_&ref=www.google.com.ar&key=20111026.OBS3314" style="display: none">');
}
if (position == 'Middle1') {
document.write ('<a href="http://uniprix.nouvelobs.com/5c/BIBLIOBS/RG_DOCUMENTS/L21/2024805832/Middle1/OasDefault/ANTHOLOGIE_BIBLIOBS_DEMI-PV_0111/bibliobs-light-10vol.gif/76682f4f706b2b32323451414142446c" target="_blank"><img src="http://uniprix.nouvelobs.com/5/BIBLIOBS/RG_DOCUMENTS/L21/2024805832/Middle1/OasDefault/ANTHOLOGIE_BIBLIOBS_DEMI-PV_0111/bibliobs-light-10vol.gif/76682f4f706b2b32323451414142446c?ref=www.google.com.ar&key=20111026.OBS3314"  alt=""  border="0"></a>');
}
if (position == 'Middle2') {
document.write ('<a href="http://uniprix.nouvelobs.com/5c/BIBLIOBS/RG_DOCUMENTS/847812370/Middle2/OasDefault/default/empty.gif/76682f4f706b2b32323451414142446c" target="_top"><img src="http://uniprix.nouvelobs.com/5/BIBLIOBS/RG_DOCUMENTS/847812370/Middle2/OasDefault/default/empty.gif/76682f4f706b2b32323451414142446c?ref=www.google.com.ar&key=20111026.OBS3314"  width="1" height="1" alt="" BORDER=0 border="0"></a>');
}
if (position == 'Middle3') {
document.write ('<TABLE cellpadding=0 cellspacing=0 align=right border=0>\n');
document.write ('<TR><TD align=center><img src="http://uniprix.nouvelobs.com/RealMedia/ads/Creatives/REALMEDIA_PAVE_0705/pub250.gif"></TD></TR>\n');
document.write ('<TR><TD>\n');
document.write ('<!--  Rubicon Project Tag -->\n');
document.write ('<!--  Site: Nouvel Observateur   Zone: Nouvel Obs  - Bottom MPU   Size: Medium Rectangle  -->\n');
document.write ('<script language="JavaScript" type="text/javascript">\n');
document.write ('var cb = Math.random();\n');
document.write ('var d = document;\n');
document.write ('var iframe = "&fr=" + (window != top);\n');
document.write ('var ref = ""; \n');
document.write ('try {\n');
document.write ('    if (window != top) {\n');
document.write ('        ref = "&rf="+escape(d.referrer);\n');
document.write ('    }\n');
document.write ('} catch (ignore) { }\n');
document.write ('d.write(');
document.write ("'");
document.write ('<script language="JavaScript" type="text/javascript"');
document.write ("'");
document.write (');\n');
document.write ('d.write(');
document.write ("'");
document.write ('src="http://optimized-by.rubiconproject.com/a/8475/13710/27298-15.js?cb=');
document.write ("'");
document.write ('+cb+ref+iframe+');
document.write ("'");
document.write ('">');
document.write ("'");
document.write (');\n');
document.write ('d.write(');
document.write ("'");
document.write ('<\\');
document.write ('/scr');
document.write ("'");
document.write ('+');
document.write ("'");
document.write ('ipt>');
document.write ("'");
document.write (');\n');
document.write ('</script>\n');
document.write ('\n');
document.write ('\n');
document.write ('</TD></TR>\n');
document.write ('</TABLE><img src="http://uniprix.nouvelobs.com/5/BIBLIOBS/RG_DOCUMENTS/L21/1731619989/Middle3/OasDefault/RUBICON_NO_PVbottom_0511/RUBICON_NO_PVbottom_0511.html/76682f4f706b2b32323451414142446c?_RM_EMPTY_&ref=www.google.com.ar&key=20111026.OBS3314" style="display: none">');
}
if (position == 'Top') {
document.write ('<a href="http://uniprix.nouvelobs.com/5c/BIBLIOBS/RG_DOCUMENTS/1701595247/Top/OasDefault/default/empty.gif/76682f4f706b2b32323451414142446c" target="_top"><img src="http://uniprix.nouvelobs.com/5/BIBLIOBS/RG_DOCUMENTS/1701595247/Top/OasDefault/default/empty.gif/76682f4f706b2b32323451414142446c?ref=www.google.com.ar&key=20111026.OBS3314"  width="1" height="1" alt="" BORDER=0 border="0"></a>');
}
if (position == 'Bottom') {
document.write ('<!--  Rubicon Project Tag -->\n');
document.write ('<!--  Site: Nouvel Observateur   Zone: Nouvel Obs - Bottom Leaderboard   Size: Leaderboard  -->\n');
document.write ('<script language="JavaScript" type="text/javascript">\n');
document.write ('var cb = Math.random();\n');
document.write ('var d = document;\n');
document.write ('var iframe = "&fr=" + (window != top);\n');
document.write ('var ref = ""; \n');
document.write ('try {\n');
document.write ('    if (window != top) {\n');
document.write ('        ref = "&rf="+escape(d.referrer);\n');
document.write ('    }\n');
document.write ('} catch (ignore) { }\n');
document.write ('d.write(');
document.write ("'");
document.write ('<script language="JavaScript" type="text/javascript"');
document.write ("'");
document.write (');\n');
document.write ('d.write(');
document.write ("'");
document.write ('src="http://optimized-by.rubiconproject.com/a/8475/13710/27299-2.js?cb=');
document.write ("'");
document.write ('+cb+ref+iframe+');
document.write ("'");
document.write ('">');
document.write ("'");
document.write (');\n');
document.write ('d.write(');
document.write ("'");
document.write ('<\\');
document.write ('/scr');
document.write ("'");
document.write ('+');
document.write ("'");
document.write ('ipt>');
document.write ("'");
document.write (');\n');
document.write ('</script>\n');
document.write ('\n');
document.write ('\n');
document.write ('\n');
document.write ('<img src="http://uniprix.nouvelobs.com/5/BIBLIOBS/RG_DOCUMENTS/L21/99736541/Bottom/OasDefault/RUBICON_NO_MBbottom_0511/RUBICON_NO_MBbottom_0511.html/76682f4f706b2b32323451414142446c?_RM_EMPTY_&ref=www.google.com.ar&key=20111026.OBS3314" style="display: none">');
}
if (position == 'Bottom1') {
document.write ('<script type="text/javascript" src="http://box.shopoon.fr/jsp/ps-box-nouvelobs-actu.js"></script>\n');
document.write ('<div id="shoppingBox"></div><img src="http://uniprix.nouvelobs.com/5/BIBLIOBS/RG_DOCUMENTS/L21/463846627/Bottom1/OasDefault/NO_RGLIVRE_PURESHOPPING_0410/PURESHOPPING_0410.html/76682f4f706b2b32323451414142446c?_RM_EMPTY_&ref=www.google.com.ar&key=20111026.OBS3314" style="display: none">');
}
if (position == 'Right1') {
document.write ('<a href="http://uniprix.nouvelobs.com/5c/BIBLIOBS/RG_DOCUMENTS/79198445/Right1/OasDefault/default/empty.gif/76682f4f706b2b32323451414142446c" target="_top"><img src="http://uniprix.nouvelobs.com/5/BIBLIOBS/RG_DOCUMENTS/79198445/Right1/OasDefault/default/empty.gif/76682f4f706b2b32323451414142446c?ref=www.google.com.ar&key=20111026.OBS3314"  width="1" height="1" alt="" BORDER=0 border="0"></a>');
}
if (position == 'TopRight') {
document.write ('<div style="display: none;"><a href="http://uniprix.nouvelobs.com/RealMedia/ads/click_lx.ads/LEQUOTIDIENAUTO/homepage/409245945/x40/default/empty.gif/33653137363261323434653333383030" target="_blank"><img src="http://uniprix.nouvelobs.com/RealMedia/ads/Creatives/default/empty.gif" alt="" border="0" height="2" width="2"></a></div><img src="http://uniprix.nouvelobs.com/5/BIBLIOBS/RG_DOCUMENTS/L21/1478517448/TopRight/OasDefault/Anti_Pixel_Default_1106/Anti_Pixel_Default_1006.html/76682f4f706b2b32323451414142446c?_RM_EMPTY_&ref=www.google.com.ar&key=20111026.OBS3314" style="display: none">');
}
if (position == 'TopLeft') {
document.write ('<a href="http://uniprix.nouvelobs.com/5c/BIBLIOBS/RG_DOCUMENTS/181703879/TopLeft/OasDefault/default/empty.gif/76682f4f706b2b32323451414142446c" target="_top"><img src="http://uniprix.nouvelobs.com/5/BIBLIOBS/RG_DOCUMENTS/181703879/TopLeft/OasDefault/default/empty.gif/76682f4f706b2b32323451414142446c?ref=www.google.com.ar&key=20111026.OBS3314"  width="1" height="1" alt="" BORDER=0 border="0"></a>');
}
if (position == 'x08') {
document.write ('<a href="http://uniprix.nouvelobs.com/5c/BIBLIOBS/RG_DOCUMENTS/1469043555/x08/OasDefault/default/empty.gif/76682f4f706b2b32323451414142446c" target="_top"><img src="http://uniprix.nouvelobs.com/5/BIBLIOBS/RG_DOCUMENTS/1469043555/x08/OasDefault/default/empty.gif/76682f4f706b2b32323451414142446c?ref=www.google.com.ar&key=20111026.OBS3314"  width="1" height="1" alt="" BORDER=0 border="0"></a>');
}
if (position == 'x09') {
document.write ('<a href="http://uniprix.nouvelobs.com/5c/BIBLIOBS/RG_DOCUMENTS/488069436/x09/OasDefault/default/empty.gif/76682f4f706b2b32323451414142446c" target="_top"><img src="http://uniprix.nouvelobs.com/5/BIBLIOBS/RG_DOCUMENTS/488069436/x09/OasDefault/default/empty.gif/76682f4f706b2b32323451414142446c?ref=www.google.com.ar&key=20111026.OBS3314"  width="1" height="1" alt="" BORDER=0 border="0"></a>');
}
}
